### ISSUE TITLE
Calendar View

### ISSUE THREAD

**Issue by lrjbrual** [lrjbrual/finance#2]
# Story

User can have the calendar view that can input the time and notes. for more details please check our notes

**Comment by deathndark** [comment]
@lrjbrual , Ok Sir I will check again the notes

**Comment by lrjbrual** [comment]
for reactjs example: https://codesandbox.io/s/m4j347534p
https://codesandbox.io/s/l98v2jjqjz
https://codesandbox.io/s/53yl751wq4

from toast UI: http://ui.toast.com/tui-calendar/
using veuJS: https://codesandbox.io/s/5xlp873rkl
https://codesandbox.io/s/j3mm6v9ky9

**Comment by deathndark** [comment]
@lrjbrual I am planning to use this javascript calendar

https://www.npmjs.com/package/react-big-calendar
https://fullcalendar.io/
https://github.com/intljusticemission/react-big-calendar/wiki/React-big-calendar-with-Rails
